<?xml version="1.0" encoding="UTF-8"?>

<!-- Defino el lenguaje que quiero
    (Gramática)
    Un lenguaje que solo tiene la marca raíz
    y dentro de ella solo puedo meter cadenas de texto
-->
<!DOCTYPE tienda[
    <!ELEMENT tienda (producto+)>
    <!ELEMENT producto (nombre, descripcion, stock)> <!-- ahora tiene un producto dentro de la etiqueta tienda-->
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT descripcion (#PCDATA)>
    <!ELEMENT stock (#PCDATA)>
    ]>
<!-- Ejemplo de uso del lenguaje-->
<tienda>
    <producto>
        <nombre>Alhambra II</nombre>
        <descripcion>Placa con FPGA ice40HX8K</descripcion>
        <stock>3</stock>
    </producto>

    <producto>
        <nombre>Icestick</nombre>
        <descripcion>Placa con FPGA ice40HX8K</descripcion>
        <stock>10</stock>
    </producto>
 
</tienda>